### ISSUE TITLE
Why no --include option? 

### ISSUE THREAD

**Issue by elgow** [rvoicilas/inotify-tools#101]
Why does inotifywait not have a `--include` option to mirror the `--exclude` one? It would be extremely useful to be able to watch a directory and complete processing of only events related to files that match a regex pattern. If it can be done for `--exclude` then why not the reverse?

**Comment by elgow** [comment]
I see that was added per another issue. I'll check why the Ubuntu package doesn't have it.

**Comment by ericcurtin** [comment]
Where was this other issue? @elgow :)

I'm curious about this option too.

**Comment by elgow** [comment]
The --include option was added in this commit  https://github.com/rvoicilas/inotify-tools/commit/20c90ec89c821fe8bb24bdad05983d15e63ea7c7  that was merged into the master branch on Oct 29, 2010.  My apt package for inotify-tools  on ubuntu 16.04 shows this version info

Version: 3.14-1ubuntu1
Depends: libc6 (>= 2.14), libinotifytools0 (>= 3.11)

It's a bit tricky to sort out what that package was built on, but it looks like it's version 3.11 while the --include option came in at inotify-tools 3.14.   So the 16.04 package seems to be built on ancient code.

**Comment by ericcurtin** [comment]
Yeah I found it... Same goes for 18.04, not included there either. I built from master --include works great there! Thanks @elgow
