### ISSUE TITLE
Error move folder

### ISSUE THREAD

**Issue by Lzhiyong** [rvoicilas/inotify-tools#103]
dir: /sdcard/Pictures/test --> /sdcard/Pictures/ppp

test dir move to ppp dir
a segmentation fault error occurred

![Screenshot_20190809-143117_Termux](https://user-images.githubusercontent.com/36750502/62759920-4e7a5e00-bab5-11e9-9b82-76be4245e884.png)

But I comment inotifytools_replace_filename(moved_from, new_name);
no segmentation fault

![Screenshot_20190809-143222_Termux](https://user-images.githubusercontent.com/36750502/62760043-9dc08e80-bab5-11e9-9504-876628ab0ac9.png)

![Screenshot_20190809-143330_Termux](https://user-images.githubusercontent.com/36750502/62760072-afa23180-bab5-11e9-8d12-397746338b98.png)

So error position at 
inotifytools_replace_filename(moved_from, new_name);

**Comment by jankratochvil** [comment]
A fix is: https://github.com/rvoicilas/inotify-tools/pull/104

**Comment by Lzhiyong** [comment]
> A fix is: #104

I have solved this problem, thank you very much.

**Comment by ericcurtin** [comment]
Merged
