### ISSUE TITLE
Any idea why this won't work?

### ISSUE THREAD

**Issue by shawnholt** [rvoicilas/inotify-tools#27]
Spent way to long on what I thought would be simple (not the first time I've done that ...)

Want to change the group of new or modified files (so apache doesn't have permission problems)

running a script in /etc/rc.local:
# !/bin/bash

inotifywait -rsm --format '%w%f' -e create -e modify ~xxxx/www/beta/sites/default/files/civicrm  ~yyyy/www/drupal/sites/defau
lt/files/civicrm || while read file;do chmod g+w $file;done

Does not seem to trigger at all when the file is created or modified ... any ideas?

**Comment by rvoicilas** [comment]
Way too late at the party, but it seems you're using the wrong operator to pipe inotifywait output: use `|` instead of `||`
