### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by yurivict** [rvoicilas/inotify-tools#55]
We use rvoicilas/inotify-tools as an upstream for FreeBSD port, but the last release has been a very long time ago, in 2010, and later commits fixed many issues that aren't released.

Thanks!

**Comment by rvoicilas** [comment]
@yurivict There's a new [3.20.0](https://github.com/rvoicilas/inotify-tools/tree/3.20.0) tag if that helps you now, more than 2 years later :)

**Comment by yurivict** [comment]
Thanks!
