### ISSUE TITLE
Stopping by to say thank you

### ISSUE THREAD

**Issue by jorinvo** [rvoicilas/inotify-tools#60]
I just would like to say thank you for creating this tool!
Works perfect for me! I wrote a little summary about my use case: https://jorin.me/homework-in-markdown/

Feel free to close this issue. 
And keep up the good work!

Greetings Jorin

**Comment by rvoicilas** [comment]
Hi @jorinvo! Thank you for your kind words - though credit for creating this tool should go to Rohan McGovern, I'm just the maintainer of this project (and not even that since I've done a poor job for the last years in maintaining it). Nice post, btw!
