### ISSUE TITLE
use option -d error

### ISSUE THREAD

**Issue by reatang** [rvoicilas/inotify-tools#62]
![image](https://cloud.githubusercontent.com/assets/8022923/14278585/03b8d684-fb5b-11e5-9b3e-19c5d55acde8.png)
Use the -m do not have this problem.

**Comment by rvoicilas** [comment]
Indeed this is an issue when `--outfile` is a relative path name - either use `-o $(realpath test-inotify.log)` for previous versions or checkout `master` as #82 fixes it. Thanks!
