### ISSUE TITLE
How can I tell which version of inotify-tools is installed?

### ISSUE THREAD

**Issue by ZillaG** [rvoicilas/inotify-tools#78]
If I compiled or installed the package I of course know which version. But if I log into a box where it's already installed, from source NOT RPMs, is there a CLI option to find out what the installed version is, e.g., inotifywatch --version? (I know inotifywatch doesn't have that option, but I just wrote it as an example).

**Comment by Szero** [comment]
Try `inotifywait --help` or `inotifywatch --help`, version should be first line of output.

**Comment by ZillaG** [comment]
Thanks!
