### ISSUE TITLE
Document that only one --exclude flag is supported

### ISSUE THREAD

**Issue by twm** [rvoicilas/inotify-tools#8]
The man page should mention that only one `--exclude` or `--excludei` flag is supported (you cannot pass two `--exclude` flags).  This is distinct from the way e.g. rsync's `--exclude` flags are logically OR'd, and can cause user confusion (I for one thought that I had a typo in my regex, and spent ages trying to figure out why my first `--exclude` wasn't matching).

Arguably a warning should be printed if one flag overrides another, as it is for having both `--exclude` and `--excludei` flags.

**Comment by mDibyo** [comment]
This is still an open issue. I was burnt by this yesterday using inotifytools on Ubuntu/Debian. Could anyone take a look.

**Comment by rvoicilas** [comment]
This has been released with [3.20.0](https://github.com/rvoicilas/inotify-tools/tree/3.20.0)
